package com.masum.cipher.core.domain.config

import com.masum.cipher.core.domain.model.TransactionCategory

object CategorizerConfig {
    val BRAND_MAPPINGS = mapOf(
        "AMAZON" to TransactionCategory.SHOPPING,
        "FLIPKART" to TransactionCategory.SHOPPING,
        "MYNTRA" to TransactionCategory.SHOPPING,
        "AJIO" to TransactionCategory.SHOPPING,
        "MEESHO" to TransactionCategory.SHOPPING,
        "NYKAA" to TransactionCategory.SHOPPING,
        "RELIANCE" to TransactionCategory.SHOPPING,
        "CROMA" to TransactionCategory.SHOPPING,
        "BLINKIT" to TransactionCategory.SHOPPING,
        "BIGBASKET" to TransactionCategory.SHOPPING,
        "ZEPTO" to TransactionCategory.SHOPPING,
        "INSTAMART" to TransactionCategory.SHOPPING,
        "JIOMART" to TransactionCategory.SHOPPING,
        "ZOMATO" to TransactionCategory.FOOD,
        "SWIGGY" to TransactionCategory.FOOD,
        "EATFIT" to TransactionCategory.FOOD,
        "DOMINOS" to TransactionCategory.FOOD,
        "KFC" to TransactionCategory.FOOD,
        "PIZZA HUT" to TransactionCategory.FOOD,
        "STARBUCKS" to TransactionCategory.FOOD,
        "MCDONALDS" to TransactionCategory.FOOD,
        "BURGER KING" to TransactionCategory.FOOD,
        "UBER" to TransactionCategory.TRANSPORT,
        "OLA" to TransactionCategory.TRANSPORT,
        "RAPIDO" to TransactionCategory.TRANSPORT,
        "INDIGO" to TransactionCategory.TRANSPORT,
        "AIR INDIA" to TransactionCategory.TRANSPORT,
        "SPICEJET" to TransactionCategory.TRANSPORT,
        "IRCTC" to TransactionCategory.TRANSPORT,
        "REDBUS" to TransactionCategory.TRANSPORT,
        "MAKEMYTRIP" to TransactionCategory.TRANSPORT,
        "GOIBIBO" to TransactionCategory.TRANSPORT,
        "BOOKMYSHOW" to TransactionCategory.ENTERTAINMENT,
        "NETFLIX" to TransactionCategory.ENTERTAINMENT,
        "SPOTIFY" to TransactionCategory.ENTERTAINMENT,
        "HOTSTAR" to TransactionCategory.ENTERTAINMENT,
        "PRIME VIDEO" to TransactionCategory.ENTERTAINMENT,
        "PVR" to TransactionCategory.ENTERTAINMENT,
        "INOX" to TransactionCategory.ENTERTAINMENT,
        "STEAM" to TransactionCategory.ENTERTAINMENT,
        "APOLLO" to TransactionCategory.HEALTH,
        "TATA 1MG" to TransactionCategory.HEALTH,
        "PHARMEASY" to TransactionCategory.HEALTH,
        "NETMEDS" to TransactionCategory.HEALTH,
        "PRACTO" to TransactionCategory.HEALTH,
        "AIRTEL" to TransactionCategory.BILLS,
        "JIO" to TransactionCategory.BILLS,
        "VODAFONE" to TransactionCategory.BILLS,
        "VI" to TransactionCategory.BILLS,
        "TATA PLAY" to TransactionCategory.BILLS,
        "GOOGLE" to TransactionCategory.BILLS,
        "PAYTM" to TransactionCategory.BILLS,
        "PHONEPE" to TransactionCategory.BILLS,
        "CRED" to TransactionCategory.BILLS,
        "GROWW" to TransactionCategory.INVESTMENT,
        "ZERODHA" to TransactionCategory.INVESTMENT,
        "UPSTOX" to TransactionCategory.INVESTMENT,
        "NAVI" to TransactionCategory.INVESTMENT,
        "FASTTAG" to TransactionCategory.TRANSPORT,
        "DUNZO" to TransactionCategory.FOOD,
        "BLINKIT" to TransactionCategory.SHOPPING,
        "ZEPTO" to TransactionCategory.SHOPPING,
        "CLEARTRIP" to TransactionCategory.TRANSPORT,
        "LENSKART" to TransactionCategory.SHOPPING,
        "FIRSTCRY" to TransactionCategory.SHOPPING,
        "URBAN COMPANY" to TransactionCategory.BILLS,
        "MAMAEARTH" to TransactionCategory.SHOPPING,
        "BOAT" to TransactionCategory.SHOPPING,
        "INDMONEY" to TransactionCategory.INVESTMENT,
        "KUVERA" to TransactionCategory.INVESTMENT,
        "FI MONEY" to TransactionCategory.INVESTMENT,
        "JUPITER" to TransactionCategory.INVESTMENT,
        "DECATHLON" to TransactionCategory.SHOPPING,
        "PAYZAPP" to TransactionCategory.BILLS,
        "MOBIKWIK" to TransactionCategory.BILLS,
        "FREECHARGE" to TransactionCategory.BILLS,

        "WALMART" to TransactionCategory.SHOPPING,
        "TARGET" to TransactionCategory.SHOPPING,
        "COSTCO" to TransactionCategory.SHOPPING,
        "TRADER JOE'S" to TransactionCategory.SHOPPING,
        "WHOLE FOODS" to TransactionCategory.SHOPPING,
        "KROGER" to TransactionCategory.SHOPPING,
        "SAFEWAY" to TransactionCategory.SHOPPING,
        "ALDI" to TransactionCategory.SHOPPING,
        "LIDL" to TransactionCategory.SHOPPING,
        "TESCO" to TransactionCategory.SHOPPING,
        "SAINSBURY'S" to TransactionCategory.SHOPPING,
        "ASDA" to TransactionCategory.SHOPPING,
        "MORRISONS" to TransactionCategory.SHOPPING,
        "MARKS & SPENCER" to TransactionCategory.SHOPPING,
        "WAITROSE" to TransactionCategory.SHOPPING,
        "BEST BUY" to TransactionCategory.SHOPPING,
        "HOME DEPOT" to TransactionCategory.SHOPPING,
        "LOWE'S" to TransactionCategory.SHOPPING,
        "APPLE" to TransactionCategory.SHOPPING,
        "IKEA" to TransactionCategory.SHOPPING,
        "ZARA" to TransactionCategory.SHOPPING,
        "H&M" to TransactionCategory.SHOPPING,
        "UNIQLO" to TransactionCategory.SHOPPING,
        "NIKE" to TransactionCategory.SHOPPING,
        "ADIDAS" to TransactionCategory.SHOPPING,
        "SEPHORA" to TransactionCategory.SHOPPING,
        "ASOS" to TransactionCategory.SHOPPING,

        "CHIPOTLE" to TransactionCategory.FOOD,
        "CHICK-FIL-A" to TransactionCategory.FOOD,
        "TACO BELL" to TransactionCategory.FOOD,
        "SUBWAY" to TransactionCategory.FOOD,
        "WENDYS" to TransactionCategory.FOOD,
        "PANERA" to TransactionCategory.FOOD,
        "DOORDASH" to TransactionCategory.FOOD,
        "GRUBHUB" to TransactionCategory.FOOD,
        "GREGGS" to TransactionCategory.FOOD,
        "COSTA COFFEE" to TransactionCategory.FOOD,
        "PRET A MANGER" to TransactionCategory.FOOD,
        "DELIVEROO" to TransactionCategory.FOOD,
        "JUST EAT" to TransactionCategory.FOOD,
        "CAFFE NERO" to TransactionCategory.FOOD,
        "NANDOS" to TransactionCategory.FOOD,

        "LYFT" to TransactionCategory.TRANSPORT,
        "BOLT" to TransactionCategory.TRANSPORT,
        "CHEVRON" to TransactionCategory.TRANSPORT,
        "SHELL" to TransactionCategory.TRANSPORT,
        "EXXON" to TransactionCategory.TRANSPORT,
        "BP" to TransactionCategory.TRANSPORT,
        "MOBIL" to TransactionCategory.TRANSPORT,
        "7-ELEVEN" to TransactionCategory.TRANSPORT,
        "CIRCLE K" to TransactionCategory.TRANSPORT,
        "WAWA" to TransactionCategory.TRANSPORT,
        "TFL" to TransactionCategory.TRANSPORT,
        "TRAINLINE" to TransactionCategory.TRANSPORT,
        "AIRBNB" to TransactionCategory.TRANSPORT,
        "BOOKING.COM" to TransactionCategory.TRANSPORT,

        "HULU" to TransactionCategory.ENTERTAINMENT,
        "DISNEY+" to TransactionCategory.ENTERTAINMENT,
        "HBO MAX" to TransactionCategory.ENTERTAINMENT,
        "APPLE TV" to TransactionCategory.ENTERTAINMENT,
        "YOUTUBE" to TransactionCategory.ENTERTAINMENT,
        "PLAYSTATION" to TransactionCategory.ENTERTAINMENT,
        "XBOX" to TransactionCategory.ENTERTAINMENT,
        "NINTENDO" to TransactionCategory.ENTERTAINMENT,

        "CVS" to TransactionCategory.HEALTH,
        "WALGREENS" to TransactionCategory.HEALTH,
        "BOOTS" to TransactionCategory.HEALTH,
        "RITE AID" to TransactionCategory.HEALTH,
        "SUPERDRUG" to TransactionCategory.HEALTH,

        "VENMO" to TransactionCategory.BILLS,
        "CASH APP" to TransactionCategory.BILLS,
        "PAYPAL" to TransactionCategory.BILLS,
        "WISE" to TransactionCategory.BILLS,
        "REVOLUT" to TransactionCategory.BILLS,
        "MONZO" to TransactionCategory.BILLS,
        "STARLING" to TransactionCategory.BILLS,
        "CHASE" to TransactionCategory.BILLS,
        "CAPITAL ONE" to TransactionCategory.BILLS,
        "AMEX" to TransactionCategory.BILLS,
        "BARCLAYS" to TransactionCategory.BILLS,
        "TIM HORTONS" to TransactionCategory.FOOD,
        "LOBLAWS" to TransactionCategory.SHOPPING,
        "NO FRILLS" to TransactionCategory.SHOPPING,
        "METRO" to TransactionCategory.SHOPPING,
        "SOBEYS" to TransactionCategory.SHOPPING,
        "CANADIAN TIRE" to TransactionCategory.SHOPPING,
        "SHOPPERS DRUG MART" to TransactionCategory.HEALTH,
        "SKIPTHEDISHES" to TransactionCategory.FOOD,
        "PETRO-CANADA" to TransactionCategory.TRANSPORT,
        "ESSO" to TransactionCategory.TRANSPORT,
        "ROGERS" to TransactionCategory.BILLS,
        "BELL" to TransactionCategory.BILLS,
        "TELUS" to TransactionCategory.BILLS,
        "WEALTHSIMPLE" to TransactionCategory.INVESTMENT,

        "WOOLWORTHS" to TransactionCategory.SHOPPING,
        "COLES" to TransactionCategory.SHOPPING,
        "BUNNINGS" to TransactionCategory.SHOPPING,
        "JB HI-FI" to TransactionCategory.SHOPPING,
        "KMART" to TransactionCategory.SHOPPING,
        "DAN MURPHY'S" to TransactionCategory.FOOD,
        "BWS" to TransactionCategory.FOOD,
        "CHEMIST WAREHOUSE" to TransactionCategory.HEALTH,
        "MENULOG" to TransactionCategory.FOOD,
        "AMPOL" to TransactionCategory.TRANSPORT,
        "TELSTRA" to TransactionCategory.BILLS,
        "OPTUS" to TransactionCategory.BILLS,
        "AFTERPAY" to TransactionCategory.BILLS,
        "ZIP" to TransactionCategory.BILLS,

        "LULU" to TransactionCategory.SHOPPING,
        "LULU HYPERMARKET" to TransactionCategory.SHOPPING,
        "CARREFOUR" to TransactionCategory.SHOPPING,
        "SPINNEYS" to TransactionCategory.SHOPPING,
        "CHOITHRAMS" to TransactionCategory.SHOPPING,
        "NOON" to TransactionCategory.SHOPPING,
        "CAREEM" to TransactionCategory.TRANSPORT,
        "TALABAT" to TransactionCategory.FOOD,
        "SALIK" to TransactionCategory.TRANSPORT,
        "ADNOC" to TransactionCategory.TRANSPORT,
        "ENOC" to TransactionCategory.TRANSPORT,
        "DU" to TransactionCategory.BILLS,
        "ETISALAT" to TransactionCategory.BILLS,
        "DEWA" to TransactionCategory.BILLS,
        "VOX CINEMAS" to TransactionCategory.ENTERTAINMENT,

        "GRAB" to TransactionCategory.TRANSPORT,
        "GRABPAY" to TransactionCategory.BILLS,
        "FAIRPRICE" to TransactionCategory.SHOPPING,
        "NTUC FAIRPRICE" to TransactionCategory.SHOPPING,
        "SHENG SIONG" to TransactionCategory.SHOPPING,
        "COLD STORAGE" to TransactionCategory.SHOPPING,
        "DON DON DONKI" to TransactionCategory.SHOPPING,
        "LAZADA" to TransactionCategory.SHOPPING,
        "SHOPEE" to TransactionCategory.SHOPPING,
        "FOODPANDA" to TransactionCategory.FOOD,
        "COMFORTDELGRO" to TransactionCategory.TRANSPORT,
        "SINGTEL" to TransactionCategory.BILLS,
        "STARHUB" to TransactionCategory.BILLS,
        "M1" to TransactionCategory.BILLS,
        "EZ-LINK" to TransactionCategory.TRANSPORT,

        "EDEKA" to TransactionCategory.SHOPPING,
        "REWE" to TransactionCategory.SHOPPING,
        "MERCADONA" to TransactionCategory.SHOPPING,
        "ALBERT HEIJN" to TransactionCategory.SHOPPING,
        "AUCHAN" to TransactionCategory.SHOPPING,
        "TOTALENERGIES" to TransactionCategory.TRANSPORT,
        "ENI" to TransactionCategory.TRANSPORT,
        "REPSOL" to TransactionCategory.TRANSPORT,
        "KLARNA" to TransactionCategory.BILLS,

        "OPENAI" to TransactionCategory.BILLS,
        "CHATGPT" to TransactionCategory.BILLS,
        "MIDJOURNEY" to TransactionCategory.BILLS,
        "ANTHROPIC" to TransactionCategory.BILLS,
        "CLAUDE" to TransactionCategory.BILLS,
        "GITHUB" to TransactionCategory.BILLS,
        "NOTION" to TransactionCategory.BILLS,
        "FIGMA" to TransactionCategory.BILLS,
        "CANVA" to TransactionCategory.BILLS,
        "ADOBE" to TransactionCategory.BILLS,
        "AIRALO" to TransactionCategory.BILLS,
        "UBER EATS" to TransactionCategory.FOOD,

        "ROBINHOOD" to TransactionCategory.INVESTMENT,
        "FIDELITY" to TransactionCategory.INVESTMENT,
        "VANGUARD" to TransactionCategory.INVESTMENT,
        "SCHWAB" to TransactionCategory.INVESTMENT,
        "COINBASE" to TransactionCategory.INVESTMENT
    )

    val KEYWORD_ANCHORS = mapOf(
        listOf("CAFE", "RESTAURANT", "DINER", "KITCHEN", "FOOD", "BAKERY", "PIZZA", "BURGER", "SWEETS", "DHABA", "COFFEE", "GRILL", "BISTRO", "PUB", "BAR") to TransactionCategory.FOOD,
        listOf("MART", "SHOP", "MALL", "FASHION", "CLOTHING", "GROCERY", "RETAIL", "SUPERMARKET", "STORE", "OUTLET", "MARKET") to TransactionCategory.SHOPPING,
        listOf("CAB", "TAXI", "METRO", "TRAIN", "FLIGHT", "AIRLINE", "PARKING", "FUEL", "PETROL", "DIESEL", "AUTO", "TOLL", "TRANSIT", "GAS") to TransactionCategory.TRANSPORT,
        listOf("CINEMA", "MOVIES", "THEATRE", "GAME", "GAMING", "CLUB", "OTT", "MUSIC", "STREAM") to TransactionCategory.ENTERTAINMENT,
        listOf("MEDICAL", "HEALTH", "CLINIC", "DENTAL", "CARE", "DRUG", "HOSPITAL", "LAB", "DIAGNOSTIC", "PHARMACY", "OPTICAL") to TransactionCategory.HEALTH,
        listOf("ELECTRIC", "WATER", "GAS", "TELECOM", "MOBILE", "INTERNET", "RECHARGE", "BILL", "UTILITY", "BROADBAND", "DTH", "PHONE", "WIRELESS") to TransactionCategory.BILLS,
        listOf("BROKING", "STOCKS", "MUTUAL FUND", "MF", "SIP", "INVESTMENT", "SECURITIES", "WEALTH", "CAPITAL", "FUND", "CRYPTO", "EQUITY") to TransactionCategory.INVESTMENT,
        listOf("SALARY", "CASHBACK", "REFUND", "INTEREST", "DIVIDEND", "PAYROLL") to TransactionCategory.INCOME
    )
}
